# Generated by Django 6.1.1 on 2026-09-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='renovado',
            field=models.BooleanField(default=False),
        ),
    ]
